# Generated by Django 4.2.5 on 2023-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pressure_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic_pressure", models.IntegerField()),
                ("diastolic_pressure", models.IntegerField()),
                ("pulse", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
