# Generated by Django 4.2.5 on 2023-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressure_data",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pressure_data",
            name="time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
